name: Spawn
version: '${project.version}'
main: com.github.miyasoku.spawn.Spawn
api-version: '1.19'
authors: [miyasoku]
description: Spawn system for Rezxis Lobby.

commands:
  spawn:
    description: Teleport to spawn.
    aliases: stuck
  setspawn:
    permission: lobby.setspawn
    description: Set the Spawnpoint.
